### PR TITLE
WIP: Added wasm/js support for webview lib. Rough implementation.

### PR DESCRIPTION
**Pull request by Xerosigma**
Cheap implementation for rough WASM support. At the very least this will allow the lib in a compose project. If someone could help finish this up that'd be great.

@KevinnZou maybe we can make a `wasm` branch in the base project to merge to?

### CODE REVIEW

**Comment by KevinnZou** [comment]
@Xerosigma Thank you for your contribution! I am planning to add support for WASM/JS. However, there is one issue - WASM requires CMP 1.6.0, which has a new resource management system incompatible with our library. A [pull request](https://github.com/KevinnZou/compose-webview-multiplatform/pull/120) has been created to solve the issue, but it has encountered some problems. You can refer to it for more information.

**Comment by KevinnZou** [comment]
@Xerosigma Thank you for your contribution! I am planning to add support for WASM/JS. However, there is one issue - WASM requires CMP 1.6.0, which has a new resource management system incompatible with our library. A [pull request](https://github.com/KevinnZou/compose-webview-multiplatform/pull/120) has been created to solve the issue, but it has encountered some problems. You can refer to it for more information.

**Comment by JagadishaIncture** [comment]
Let us know from which version its will support for Webassembly ?

**Comment by JagadishaIncture** [comment]
@Xerosigma iframe may not support some urls due to security.

**Comment by KevinnZou** [comment]
> pull request

@JagadishaIncture I am sorry that we may not currently plan to support wasm/js. You are welcome to work on this [PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/154)

**Pull request closed without merging**
