### PR TITLE
fix(backgroundColor issue): ios add opaque params default true

### PR DESCRIPTION
**Pull request by riveronly**
fix since 1.8.6 version issue that backgroundColor can scroll and status bar‘s backgroundColor is transparent, which add switch param ``opaque``.

### CODE REVIEW

**Comment by riveronly** [comment]
https://github.com/KevinnZou/compose-webview-multiplatform/assets/42523296/adb5e478-30ab-4f3f-9dfb-ef3522cbe2f0

**Comment by riveronly** [comment]
https://github.com/KevinnZou/compose-webview-multiplatform/assets/42523296/262b44e6-0587-4609-9857-6a90134e3397

**Comment by riveronly** [comment]
code style refine

**Comment by KevinnZou** [comment]
@riveronly Thanks for your contribution. I am currently traveling and will begin reviewing this PR next week. Thank you again!

**Comment by KevinnZou** [comment]
@msasikanth Could you also have a review on this PR? Thanks!

**Comment by riveronly** [comment]
restore original format

**Comment by riveronly** [comment]
@KevinnZou  please delete this PR and I will resubmit it

**Comment by msasikanth** [comment]
> @KevinnZou I accidentally used the wrong email address to submit. Can you submit a work order to github to delete this mr? This is very important to me, thank you.

I don't think there is a way to delete the PR on GitHub. The only option is to close it, if it has to be deleted it needs to be from GitHub support (which I don't think will happen in most scenarios).

**Comment by msasikanth** [comment]
fwiw I see only the last commit in this PR has a different username. So, you can just drop that commit and force push to your repo. That should clear it.

**Comment by riveronly** [comment]
Removing commit and force push will change the header information and it will not be the same merge request. Merge request records can be deleted only if github supports it. But there is no other way to delete this commit.

**Comment by KevinnZou** [comment]
@riveronly I found that you already submitted a new [PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/165). We can directly review that one and dismiss this one.

**Pull request closed without merging**
