### PR TITLE
Upgrade deps version

### PR DESCRIPTION
**Pull request by alirezat775**
Hey @KevinnZou In this PR, I updated dependencies to the new available version, and, since the new compose version has been released I updated it,
Plus the new version had some breaking changes and I fixed them.

Thank you in advance for reviewing this PR

### CODE REVIEW

**Comment by KevinnZou** [comment]
@alirezat775 Thank you for your contribution! That is exactly what I am planning to do! I will review and test it soon!

**Review by KevinnZou — COMMENTED** [review]
@alirezat775 Great job! I have one question: According to the [official instructions](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0), we need to place the file under the `composeResources` folder in order to make it detectable. However, our HTML files are still located in the `resources/assets` folder. Do we need to move them? And if we do, will it affect their position within the platform package?

**Comment by alirezat775** [comment]
@KevinnZou Thank you for the review, the new resource directory has been applied based on your feedback and [Documentation](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html#raw-files) also, I moved the HTML path's decision to the app level from the common level, to make sure we do not restrict any platform, but we need to mention in the doc or release note that after this change, using resources must be compatible with new compose version.

**Comment by KevinnZou** [comment]
@alirezat775 Thank you for your work! However, when I tested it locally, I found that it did not work on Android. I think the issue may be that the HTML files are not being packaged to the Android file system after being moved to the composeResource folder. I have already submitted this [issue](https://github.com/JetBrains/compose-multiplatform/issues/4503) to Jetbrains.

To resolve the issue, we can revert to the previous version where the file was stored in the `resources` folder. But this will violate the official instructions. Do you have any suggestions?

**Comment by alirezat775** [comment]
@KevinnZou Thanks for submitting the issue on the CMP side, I'm not sure about the side effect of reverting the composeResource to the previous version, it opens the incompatibility door for webview's users. they have to maintain 2 packaging structures, one for KMP, and one for webview library because we made it non-standard.

**Comment by KevinnZou** [comment]
@alirezat775 Yes, I agree that it would be best to align with the KMP resource structure. Let's wait for an official response and work together to find a solution for this issue.

**Comment by KevinnZou** [comment]
@alirezat775 I found a solution to the previous issue. We just need to place the HTML files under the `composeResource/assets` folder, and everything will work as before. I have submitted a new [pull request](https://github.com/KevinnZou/compose-webview-multiplatform/pull/140) based on this one, can you please review it?

**Comment by alirezat775** [comment]
I'm declining this PR because of [another implementation ](https://github.com/KevinnZou/compose-webview-multiplatform/pull/140)

**Pull request closed without merging**
