### PR TITLE
Updated jcef to latest version and KCEF for improved custom request context handler

### PR DESCRIPTION
**Pull request by DatL4g**

### CODE REVIEW

**Comment by KevinnZou** [comment]
@DatL4g Great Job! Thank you so much!

**Comment by KevinnZou** [comment]
@DatL4g One issue I encountered is that you are using the `KCEFResourceRequestHandler` for request interception. However, it only has the `onBeforeResourceLoad` method, which will be called multiple times for a single URL request. Is it possible to provide the `CefRequestHandlerAdapter` instead, so that we can override the `onBeforeBrowse` method, which will only be called once for each URL request?

**Comment by DatL4g** [comment]
@KevinnZou this should be no problem now. You can call this method on the client `addRequestHandler`

**Comment by KevinnZou** [comment]
@DatL4g So the issue you mentioned in this [link](https://github.com/KevinnZou/compose-webview-multiplatform/issues/37#issuecomment-1831988798) has been solved? It appears that you have provided a default `CefResourceRequestHandler`, but the default `CefRequestHandler` is still missing. So should the same problem still exist if we just call `addRequestHandler` which will override the default implementation?

Update: I have tested it with the latest KECF version and confirmed that the problem still exists.

**Pull request merged**
